//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnjizaraDBEntities : DbContext
    {
        public KnjizaraDBEntities()
            : base("name=KnjizaraDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autori> Autoris { get; set; }
        public virtual DbSet<Knjige> Knjiges { get; set; }
        public virtual DbSet<Knjige_Zanr> Knjige_Zanr { get; set; }
        public virtual DbSet<Korisnici> Korisnicis { get; set; }
        public virtual DbSet<Narudzbina> Narudzbinas { get; set; }
        public virtual DbSet<Narudzbina_Knjiga> Narudzbina_Knjiga { get; set; }
        public virtual DbSet<Omiljeno> Omiljenoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VrstaKorisnika> VrstaKorisnikas { get; set; }
        public virtual DbSet<Zanr> Zanrs { get; set; }
    }
}
