//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnici()
        {
            this.Narudzbinas = new HashSet<Narudzbina>();
            this.Omiljenoes = new HashSet<Omiljeno>();
        }

        public int id_osoba { get; set; }

        [RegularExpression(@"^[a-zšðèæžA-ZŠÐÈÆŽ]+(\s[a-zšðèæžA-ZŠÐÈÆŽ]+)?$", ErrorMessage = "Numericki karakteri nisu dozvoljeni.")]
        [Required(ErrorMessage = "Unesite ime!")]
        public string ime { get; set; }

        [RegularExpression(@"^[a-zšðèæžA-ZŠÐÈÆŽ]+(\s[a-zšðèæžA-ZŠÐÈÆŽ]+)?$", ErrorMessage = "Numericki karakteri nisu dozvoljeni.")]
        [Required(ErrorMessage = "Unesite prezime!")]
        public string prezime { get; set; }

        [Required(ErrorMessage = "Izaberite pol!")]
        public string pol { get; set; }

        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Nije validan broj telefona.")]
        [Required(ErrorMessage = "Unesite broj telefona!")]
        public string telefon { get; set; }

        public Nullable<int> id_vrsta_korisnika { get; set; }

        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
            ErrorMessage = "Email adresa nije validna.")]
        //[DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Unesite email!")]
        public string email { get; set; }

        [Remote("IsUsernameExist", "Korisnici", ErrorMessage = "Korisnicko ime vec postoji.")]
        [Required(ErrorMessage = "Unesite korisnicko ime!")]
        public string korisnicko_ime { get; set; }

        [DataType(DataType.Password)]
        [MaxLength(30, ErrorMessage = "Lozinka moze imati maksimalno 30 karaktera.")]
        [MinLength(4, ErrorMessage = "Lozinka mora imati minimalno 4 karaktera.")]
        [Required(ErrorMessage = "Unesite lozinku!")]
        public string lozinka { get; set; }

        //[Required(ErrorMessage = "Potvrdite lozinku!")]
        //[DataType(DataType.Password)]
        //[System.ComponentModel.DataAnnotations.Compare("lozinka", ErrorMessage = "Lozinke se ne poklapaju, Pokusajte ponovo!")]
        //public string PotvrdjenaLozinka { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbina> Narudzbinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Omiljeno> Omiljenoes { get; set; }
        public virtual VrstaKorisnika VrstaKorisnika { get; set; }
    }
}
