//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbina()
        {
            this.Narudzbina_Knjiga = new HashSet<Narudzbina_Knjiga>();
        }
    
        public int id_narudzbine { get; set; }
        public int id_osoba { get; set; }
        public System.DateTime datum { get; set; }
        public string status { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbina_Knjiga> Narudzbina_Knjiga { get; set; }
    }
}
