//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Omiljeno
    {
        public int id_omiljeno { get; set; }
        public Nullable<int> id_osoba { get; set; }
        public Nullable<int> id_knjige { get; set; }
    
        public virtual Knjige Knjige { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
