//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Zanr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zanr()
        {
            this.Knjige_Zanr = new HashSet<Knjige_Zanr>();
        }
    
        public int id_zanr { get; set; }

        [Remote("IsGenreExist", "Zanr", ErrorMessage = "Zanr vec postoji.")]
        [MaxLength(50, ErrorMessage = "Naziv knjige moze imati maksimalno 50 karaktera.")]
        [RegularExpression(@"^[a-zšðèæžA-ZŠÐÈÆŽ]+(\s[a-zšðèæžA-ZŠÐÈÆŽ]+)?$", ErrorMessage = "Numericki karakteri nisu dozvoljeni.")]
        [Required(ErrorMessage = "Ovo polje je obavezno!")]
        public string vrsta { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knjige_Zanr> Knjige_Zanr { get; set; }
    }
}
